name: Generate GitHub Stats

on:
  push:                     # run on every commit
  schedule:
    - cron: "0 0 * * 0"     # run every Sunday at midnight UTC
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Download GitHub Stats
      - name: Download GitHub Stats
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=MdAfzaalkhan&show_icons=true&theme=radical&count_private=true&hide_border=true" -o stats.svg

      # Download Streak Stats
      - name: Download Streak Stats
        run: |
          curl -s "https://streak-stats.demolab.com?user=MdAfzaalkhan&theme=radical&hide_border=true" -o streak.svg

      # Download Top Languages
      - name: Download Top Languages
        run: |
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=MdAfzaalkhan&layout=compact&theme=radical&count_private=true&hide_border=true" -o langs.svg

      # Commit updated files
      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg streak.svg langs.svg
          git commit -m "Update GitHub stats"
          git push
