name: Generate GitHub Stats

on:
  push:                     # run on every commit
  schedule:
    - cron: "0 0 * * 0"     # run every Sunday at midnight UTC
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # GitHub Stats Card
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          PAT_1: ${{ secrets.Readme_Stats }}
        with:
          username: MdAfzaalkhan
          show_icons: true
          theme: radical
          cache_seconds: 604800
          output: ./stats.svg

      # Streak Stats Card
      - name: Download Streak Stats
        run: |
          curl -o streak.svg "https://streak-stats.demolab.com?user=MdAfzaalkhan&theme=radical&hide_border=true"

      # Top Languages Card
      - name: Generate Top Languages
        run: |
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=MdAfzaalkhan&layout=compact&theme=radical"

      # Commit generated files
      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg streak.svg langs.svg
          git commit -m "Update GitHub stats"
          git push
